#!/usr/bin/env sh
. "$(pwd)/.husky/_/husky.sh"
# . "$(dirname "$0")/_/husky.sh"
# echo "Running lint..."
# npm run lint
echo "Running tests..."
npm test
echo "Running fix:package..."
npm run fix:package
